[MessageControl] Making the plugin work in-process only, separating Logging and Tracing functionality
WebPlatformForEmbedded/ThunderNanoServicesRDK pull request #235
Opened 2023-05-09 13:06 UTC by VeithMetro

2023-05-19 11:11 UTC, sebaszm requested changes
See comments.

2023-05-19 13:33 UTC, VeithMetro reviewed
See comments

2023-05-19 13:33 UTC, VeithMetro commented on MessageControl/MessageControl.h
>              if (id == _connectionId) {
Can we get rid of the `_connectionId` class member entirely then, if it is not need for `IRemoteConnection`, or does it need to stay for this part?

2023-05-24 08:04 UTC, sebaszm approved these changes

2023-05-24 13:07 UTC, pwielders approved these changes
I put my trust in @sebaszm :-)

2023-05-24 15:46 UTC, merged